[package]
name = "computer_viz"
version = "0.1.0"
authors = ["joemclo8 <joemclo8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluetooth-serial-port = "0.6.0"
cobs = "0.1.4"
byteorder = "1.3.4"